Controllers/ContatoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _2MVC.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;
namespace _2MVC.Controllers;

public class ContatoController : Controller
{
    private readonly ILogger<ProjetoController> _logger;

    public ContatoController(ILogger<ProjetoController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
}

Controllers/ProjetoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _2MVC.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore;

namespace _2MVC.Controllers;

public class ProjetoController : Controller
{
    private readonly ILogger<ProjetoController> _logger;
    private readonly GestaoContext _context;

    public ProjetoController(ILogger<ProjetoController> logger, GestaoContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }
    public async Task<IActionResult> ProjetosIndex()
    {
        var projetos = await _context.Projetos.Where(p => p.Status == 0).ToListAsync();
        return View(projetos);
    }
    public IActionResult ProjetosAdicionar()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ProjetosAdicionar(Projeto projeto)
    {
        if (ModelState.IsValid)
        {
            await _context.Projetos.AddAsync(projeto);
            await _context.SaveChangesAsync();
            return RedirectToAction("ProjetosIndex");
        }
        return View(projeto);
    }

    [HttpPost]
    public async Task<IActionResult> ProjetosCancelar(int Idprojeto)
    {
        //EU NÃO EXCLUO OS PROJETOS, APENAS MUDO O STATUS PARA 2
        Console.WriteLine(Idprojeto);
        if (ModelState.IsValid)
        {
            
            var projetoDelete = await _context.Projetos.FindAsync(Idprojeto);
            if (projetoDelete != null)
            {
                projetoDelete.Status = 2; // Cancelado
                await _context.SaveChangesAsync();
            }
        }
        return RedirectToAction("ProjetosIndex");
    }

    [HttpGet("ProjetosDetalhes/{idProjeto}")]
    public async Task<IActionResult> ProjetosDetalhesGet(int IdProjeto)
    {
        var projeto = await _context.Projetos.FindAsync(IdProjeto);
        if (projeto == null)
        {
            return NotFound();
        }
        var tarefas = await _context.Tarefas.Where(t => t.IdProjeto == IdProjeto).ToListAsync();
        ViewBag.Tarefas = tarefas;
        return View("ProjetosDetalhes",projeto);
    }

    [HttpPost]
    public async Task<IActionResult> ProjetosDetalhes(int IdProjeto)
    {
        if (ModelState.IsValid)
        {

            var projeto = await _context.Projetos.FindAsync(IdProjeto);
            if (projeto != null)
            {
                var tarefas = await _context.Tarefas.Where(t => t.IdProjeto == IdProjeto).ToListAsync();
                ViewBag.Tarefas = tarefas;
                return View(projeto);
            }
        }
        return RedirectToAction("ProjetosIndex");
    }

    

    [HttpPost]
    public async Task<IActionResult> ProjetosEditar(Projeto projeto)
    {
        if (ModelState.IsValid)
        {
            var projetoEdit = await _context.Projetos.FindAsync(projeto.IdProjeto);
            if (projetoEdit != null)
            {
                projetoEdit.Nome = projeto.Nome;
                projetoEdit.Descricao = projeto.Descricao;
                projetoEdit.DataInicio = projeto.DataInicio;
                projetoEdit.DataFim = projeto.DataFim;
                await _context.SaveChangesAsync();
            }
        }
        return RedirectToAction("ProjetosIndex");
    }

    [HttpPost]
    public async Task<IActionResult> ProjetosConcluir(int IdProjeto)
    {
        if (ModelState.IsValid)
        {
            var projeto = await _context.Projetos.FindAsync(IdProjeto);
            if (projeto != null)
            {
                projeto.Status = 1; // Concluído
                await _context.SaveChangesAsync();
            }
        }
        return RedirectToAction("ProjetosIndex");
    }

    public async Task<IActionResult> ProjetosConcluido()
    {
        var projetos = await _context.Projetos.Where(p => p.Status == 1).ToListAsync();
        return View(projetos);
    }

    public async Task<IActionResult> ProjetosCancelados()
    {
        var projetos = await _context.Projetos.Where(p => p.Status == 2).ToListAsync();
        return View(projetos);
    }

    [HttpPost]
    public async Task<IActionResult> ProjetosExcluir(int IdProjeto)
    {
        if (ModelState.IsValid)
        {
            var projeto = await _context.Projetos.FindAsync(IdProjeto);
            if (projeto != null)
            {
                _context.Projetos.Remove(projeto);
                await _context.SaveChangesAsync();
            }
        }
        return RedirectToAction("ProjetosIndex");
    }


    public async Task<IActionResult> ProjetosAtivar(int IdProjeto)
    {
        if (ModelState.IsValid)
        {
            var projeto = await _context.Projetos.FindAsync(IdProjeto);
            if (projeto != null)
            {
                projeto.Status = 0; // Em Andamento
                await _context.SaveChangesAsync();
            }
        }
        return RedirectToAction("ProjetosIndex");
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <script type="importmap"></script>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/headerFooterStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_2MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Projeto" asp-action="Index">
                    <img src="~/homeIcon.ico" alt="Home"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Projeto" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Projeto" asp-action="ProjetosIndex">Projetos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
    <div class="footer-content">
        <div class="footer-text">
        © 2025 Gabriel Cassio Alexandre Olímpio. Todos os direitos reservados.
        </div>
        
        <div class="footer-icon">
        <svg width="22" height="22" fill="#171515" viewBox="0 0 24 24"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.387.6.113.82-.258.82-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.084-.729.084-.729 1.205.084 1.84 1.236 1.84 1.236 1.07 1.834 2.809 1.304 3.495.997.108-.775.418-1.304.762-1.604-2.665-.305-5.466-1.334-5.466-5.931 0-1.31.469-2.381 1.236-3.221-.124-.303-.535-1.523.117-3.176 0 0 1.008-.322 3.301 1.23a11.52 11.52 0 0 1 3.003-.404c1.018.005 2.045.138 3.003.404 2.291-1.553 3.297-1.23 3.297-1.23.653 1.653.242 2.873.119 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.803 5.624-5.475 5.921.43.371.823 1.102.823 2.222v3.293c0 .322.218.694.825.576C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
        </div>

        <div class="footer-links">
        <a href="https://github.com/biel081107" target="_blank">GitHub</a>
        <a href="/contato">Contato</a>
        </div>
    </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>